spring:
  profiles:
    include: basic
  cloud:
    nacos:
      discovery:
        server-addr: "127.0.0.1:8848"
  datasource:
    url: jdbc:mysql://192.168.3.200:3306/authentication?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: password
    initialization-mode: always