spring:
  application:
    name: wy-authentication
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate.ejb.identifier_generator_strategy_provider: com.wenyu7980.data.jpa.generator.IdGeneratorStrategyProvider
  datasource:
    schema:
      - classpath:sql/schema-authentication.sql
    data:
      - classpath:sql/data-authentication.sql
feign:
  hystrix:
    enabled: true