server:
  port: 8001
spring:
  application:
    name: wy-authentication
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate.ejb.identifier_generator_strategy_provider: com.wenyu7980.data.jpa.generator.IdGeneratorStrategyProvider
  datasource:
    schema:
      - classpath:schema-authentication.sql
    data:
      - classpath:data-authentication.sql