server:
  port: 8002
spring:
  application:
    name: wy-authentication
  datasource:
    jpa:
      hibernate:
        ddl-auto: validate
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    schema:
      - classpath:schema-authentication.sql
logging:
  level:
    com.wenyu7980.authentication.common: debug